(define-module (yumieko theme)
  #:use-module (haunt site)
  #:use-module (haunt post)
  #:use-module (haunt utils)
  #:use-module (haunt builder blog)
  #:use-module (srfi srfi-19)
  #:use-module (ice-9 match)
  #:use-module (ice-9 string-fun)
  #:use-module (sxml match)
  #:export (yumieko-theme))

(define (navbar site title)
  `(nav (@ (class "navbar navbar-expand-sm sticky-top"))
	(div (@ (class "container-fluid"))
	     (a (@ (href "/")
		   (class "navbar-brand"))
		(img (@ (src "/images/yumieko.svg")
			(alt "YumiEko")
			(class "scaled-svg")))
		(span ,(site-title site)))
	     (span (@ (class "nav-title mx-auto")) ,title)
	     (div (@ (class "d-flex gap-2"))
                  (a (@ (href "https://www.yumieko.com/") (class "nav-link")) "秘密基地")
		  (a (@ (href "/archives") (class "nav-link")) "归档")
		  (a (@ (href "/tags") (class "nav-link")) "标签")
                  (a (@ (href "/friends.html") (class "nav-link")) "友链")
                  (a (@ (href "/about.html") (class "nav-link")) "关于")))))

(define (footer site)
  `(footer (@ (class "footer"))
	   (div (@ (class "copyright"))
		(div (p "© " ,(number->string (date-year (current-date))) " Minkie Yume 版权所有。"
			"本站资产由 "
			(a (@ (href "/posts/peer-production-license.html"))
			   "PPL")
			" 协议授权，源代码由 "
			(a (@ (href "https://www.gnu.org/licenses/gpl-3.0.en.html"))
			   "GPL3.0")
			" 协议授权。")
		     (p "Power by "
			(a (@ (href "https://dthompson.us/projects/haunt.html"))
			   "haunt")
			" ,source can be found "
			(a (@ (href "https://github.com/minkieyume/kikowiwuri"))
			   "here"))))))

(define (parse-post-toc post)
  (let loop ((sxml (post-sxml post))
             (result '()))
    (match sxml
      (() (reverse result) )
      ((`(,hl (@ (id ,hid)) ,headline)  tail ...)
       (if (char=? #\h (string-ref (symbol->string hl) 0))
           (loop tail (cons `(li (a (@ (href ,(string-append "#" hid)))
                                    ,headline))
                            result))
           (loop tail result)))
      ((head . tail)
       (loop tail result)))))

(define (convert-summary post-summary)
  (if post-summary
      (map (lambda (sm)
	     `(p ,sm)) (string-split post-summary #\tab))
      #f))

(define (sidebar-right site)
  `(aside (@ (class "sidebar-right"))
	  (div (@ (class "sidebar-widget"))
               (div (@ (class "sidebar-widget-title")) "链接")
               (div (@ (class "subscribe-links"))
                    (a (@ (href "/feed.xml")) "✦ 订阅 (Atom)")
		    (a (@ (href "/rss2.xml")) "✦ 订阅 (RSS)")))
	  (div (@ (class "sidebar-widget"))
               (div (@ (class "sidebar-widget-title")) "个人")
               (div (@ (class "subscribe-links"))
		    (a (@ (href "/saikin.html")) "✦ 最近在干嘛？")
		    (a (@ (href "/use.html")) "✦ 爱用什么玩意？")
		    (a (@ (href "/suki.html")) "✦ 喜欢什么东西？")
		    (a (@ (href "/suki-sites.html")) "✦ 推荐什么网站？")))))

(define (yumieko-layout site title body)
  `((doctype "html")
    (html (@ (lang "zh-CN")))
    (head
     (meta (@ (charset "utf-8")))
     (meta (@ (name "viewport")
              (content "width=device-width, initial-scale=1")))
     (link (@ (href "/assets/bootstrap/css/bootstrap.min.css")
	      (rel "stylesheet")))
     (script (@ (src "/assets/bootstrap/css/js/bootstrap.bundle.min.js")))
     (link (@ (href "/assets/style.css")
	      (rel "stylesheet")))
     (meta (@ (property "og:title")
              (content
               ,(string-append title
                               " — "
                               (site-title site)))))
     (meta (@ (property "og:site_name")
              (content ,(site-title site))))
     (meta (@ (property "og:image")
              (content "/yumemi/creator/kikowiwuri/yumieko/main/web-app-manifest-512x512.png")))
     (meta (@ (name "fediverse:creator")
              (content "minkieyume@kikowiwu.com")))
     (title ,(string-append title " — " (site-title site)))
     (link (@ (rel "alternative")
              (href "/feed.xml")
              (title ,(site-title site))
              (type "application/atom+xml")))
     (link (@ (rel "alternative")
              (href "/rss2.xml")
              (title ,(site-title site))
              (type "application/rss+xml")))
     (link (@ (rel "icon")
	      (type "image/png")
	      (href "/favicon-96x96.png")
	      (sizes "96x96")))
     (link (@ (rel "icon")
	      (type "image/svg+xml")
	      (href "/favicon.svg")))
     (link (@ (rel "shortcut icon")
	      (href "/favicon.ico")))
     (link (@ (rel "apple-touch-icon")
	      (sizes "180x180")
	      (href "/apple-touch-icon.png")))
     (link (@ (rel "manifest")
	      (href "/site.webmanifest"))))
    (body
     ,(navbar site title)
     (div (@ (class "container main"))
	  (div (@ (class "container eko"))
	       ,body)
	  ,(sidebar-right site))
     ,(footer site))))

(define (yumieko-post post)
  `(article (@ (class "post-content"))
            (h1 (@ (class "post-title")) ,(post-title post))
            (div (@ (class "post-meta"))
		 (span "| ")
		 (span ,(string-append "By "(post-author post)))
		 (span " ✦ ")
                 (span ,(date->string (post-date post) "~Y 年 ~m 月 ~d 日"))
		 (span " |"))
	    (div (@ (class "post-summary")) ,@(convert-summary (post-ref post 'summary)))
            (div (@ (class "post-body"))
                 ,@(post-sxml post))))

(define (yumieko-pagination site body previous-page next-page)
  `((,@body
     (div (@ (class "pagination"))
          ,(if previous-page
               `(a (@ (class "btn")
                      (href ,previous-page))
                   "← 上一页")
               `(a (@ (class "btn disabled"))
                   "← 上一页"))
          (a (@ (class "btn") (href "/")) " 主页 ")
          ,(if next-page
               `(a (@ (class "btn")
                      (href ,next-page))
                   "下一页 →")
               `(a (@ (class "btn disabled"))
                   "下一页 →"))))))

(define (post-card post)
  (let ((summary (convert-summary (post-ref post 'summary)))
	(title (post-title post))
	(date (date->string (post-date post) "~Y 年 ~m 月 ~d 日")))
    `(article (@ (class "post-card"))
              (h2 (a (@ (href ,(string-append "/posts/" (post-slug post) ".html")))
                     ,title ,@(if date `(" - " ,date) '())))
              ,@(if summary `((div (@ (class "post-summary")) ,@summary)) '()))))

(define (yumieko-post-collections site title posts prefix)
  `(div (@ (class "post-list"))
	(h1 ,title)
        ,@(map post-card posts)))

(define yumieko-theme
  (theme #:name "yumieko"
	 #:layout yumieko-layout
	 #:post-template yumieko-post
	 #:collection-template yumieko-post-collections
	 #:pagination-template yumieko-pagination))
