#+title: 终末之旅开发日志#4
#+date: 2021-12-17T15:41:57
#+modified: 2026-03-01T15:41:57
#+tags: 终末之旅 日志归档 游戏日志 创作日志
#+summary: https://hive.indienova.com/farm/blog/2021/12/u-4025459125020rYp.jpg	这周的主要工作是调整了角色的奔跑和跳跃机制。让角色能实现简单的跑酷，为此我做了一张简洁的跑酷测试用小地图，经过一整天的代码调整，参考网上搜索到的一些代码教程，终于把我的角色的跳跃代码调整到了一个比较令自己满意的程度。
https://hive.indienova.com/farm/blog/2021/12/u-4025459125020rYp.jpg

这周的主要工作是调整了角色的奔跑和跳跃机制。让角色能实现简单的跑酷，为此我做了一张简洁的跑酷测试用小地图，经过一整天的代码调整，参考网上搜索到的一些代码教程，终于把我的角色的跳跃代码调整到了一个比较令自己满意的程度。

然后就是着手设计游戏更具体的方面的机制和玩法了。

首先是HUD，为了设计HUD，参考了一些别的2D横版游戏的HUD，并结合自己思考绘制了一张草图。

https://hive.indienova.com/farm/blog/2021/12/u-4025459125359avy.jpg

最左边的HUD分别是代表疲劳值、饥饿值和温度。为了保证游戏节奏比较平缓，让玩家能慢慢享受旅行的乐趣，所以我没有给角色加入生命值的设定，而是用疲劳值取代，如果疲劳值过低，玩家行动会变的特别缓慢、无法跳跃，需要在原地露营才能恢复，这样一来，边旅行和探索废墟，边露营便成了游戏的核心玩法。特定区域温度会发生变动，这样也会影响玩家的行动，玩家必须穿保暖的衣服或者用取冷的工具等，来在温度不适合的区域方便前行。

中间的HUD代表的是物品栏和快乐度，玩家的快乐度也会影响玩家的行动能力，以及两个主角之间的互动。

最右边的代表时间，游戏中的一些元素，还有景象等，会随着时间的流逝而改变，这是将来要实现的想法之一。

目前最左边的HUD已经成功做到基础的实现，虽然并不好看，不过之后有了美工应该会好很多了。

设计的思考模式来自《游戏设计艺术》这本书中的有些元素是机制这一章节，根据这章提供的游戏空间的思考模式和思路，我成功把游戏地图生成机制的设计和游戏核心玩法机制的设计也绘制在了本子上。

https://hive.indienova.com/farm/blog/2021/12/u-4025459125950lLf.jpg

为了让玩家体验到充满不确定性，不可思议的旅途，因此我使用了离散空间的方式设计游戏的地图，把一个个场景看作一个个离散的点，通过这些离散的点之间随机生成链接，便可以让地图充满不确定性。

而为了保证连贯性，我的做法是先把地图分为多个不同的大区域，每个区域看作离散的点随机链接，而大区域中，又有许多离散随机链接的点作为小区域。

在每一个小区域中，则会设计多个不同方向的场景切换通路。

除了上下左右，还有些地方可以通过互动按键进入前后场景，这样能让2D游戏也实现像3维空间一样切换的地图模式。

其中各个场景的部分房间，也可以采用随机化生成，但同时也可以设计一些固定的场景房间，来保证地图的整体性和连贯性。需要有随机性，但又不能太过随机。

https://hive.indienova.com/farm/blog/2021/12/u-40254591262643Dy.jpg

然后就是游戏的核心玩法，我用这样的图指明了玩家可以在游戏中做的一些行为和状态之间的关系。

总之，这周的游戏游戏又有一些进展，下周可以再接再厉。
