#+title: 终末之旅开发日志#1
#+date: 2021-11-26T15:36:20
#+modified: 2026-03-01T15:36:20
#+tags: 终末之旅 日志归档 游戏日志 创作日志
#+summary: 梦启航的地方，也是旅途开始的地方	最近有打算开发一款游戏，想要传达给玩家一种和伙伴在废墟自由自在旅行的美好体验。所以我决定先着手去做了，开发过程中遇到问题再慢慢解决。	这个游戏要给玩家一种在废墟中悠闲旅行的感觉，同时也要让玩家从两位主角之间密不可分的友情中体验到温馨和美好的感受。
梦启航的地方，也是旅途开始的地方

最近有打算开发一款游戏，想要传达给玩家一种和伙伴在废墟自由自在旅行的美好体验。所以我决定先着手去做了，开发过程中遇到问题再慢慢解决。

这个游戏要给玩家一种在废墟中悠闲旅行的感觉，同时也要让玩家从两位主角之间密不可分的友情中体验到温馨和美好的感受。

首先遇到的是如何传达这款游戏的体验，关于这个我列了个表格，里面记录了我想要传达给玩家的所有体验以及对于如何实现这些体验的一些想法，我分析了下这些想法，大致上主题都离不开友谊和旅行两点，这样游戏的主题就确定下来了：末世中自由的旅途与友谊。后面再列出一些子主题，以后游戏的设计围绕着这个统一的大主题和细分的一些子主题就好了。

看了一些游戏设计的教程，也做了一些表格，大致可以确定这个游戏的核心是：

一个和伙伴一起旅行且能让玩家感受到温馨，脱离社会拘束的自由的，慢节奏生存探索向末世废墟风游戏。

然后我做了张思维导图，把自己关于游戏机制方面的构思发散思考了一下，关于如何从机制方面体现旅途的感觉，如何从机制方面塑造温馨感，以及如何从机制方面思考玩家与游戏中元素的互动之类的。

大概机制可以分为旅行、探索和伙伴三个方向，至于生存和沙盒元素还有待思考。

旅行方面大概就是，玩家可以借助自己的载具旅行，走得更远，旅途中会遇到各种新奇的事物，可能会有一些偶然的事件，玩家可以在旅途中边旅行边探索，四海为家的感受。载具需要燃料支撑，玩家也需要寻找食物和水源，这样就有更多的动机来参与探索，感受到旅途的乐趣，打算通过随机化地图生存来增加旅途的不确定性和玩家的惊喜感，路上也可以插入一些不错的故事事件等。

探索方面，打算做一些需要协作来解决的谜题之类的，但是不能太难，不能影响到游戏本身的风格和主题定位，里面可以加入一些特别的奖励，比如需要的一些资源，还有一些不错的，特别的美景，整个游戏节奏打算做成慢节奏的，可以让玩家悠闲地享受旅途和探索的乐趣。

然后是伙伴，这方面打算重点塑造，我一直在思考的是一个问题：

如何利用合理的游戏机制，塑造出两个游戏角色不可分割的友情方面的联系？

如果抛开这个问题不谈，那么我的想法一个是设计成双人游戏，另一个塑造一个能给人很好的体验的NPC作为另一个与你一同旅行的伙伴。还有就是打算在前面两个想法的基础上增加一些两个角色的有趣互动，以及通过一些故事和剧情的塑造让玩家体验到主角之间的友情。还有就是关于友情的一些隐藏数值的引入，这些都是我目前能想到的。虽然这些想法对上面的问题解决有一定帮助，但是总感觉还不够问题，更好的想法还在构思中。

然后就是游戏要做成什么类型的问题，最开始的构思是3D末世生存探索类游戏，但是思考了下，发现并没有足够的条件去开发3D游戏，且做成3D的话，很可能项目会特别大，导致工期太长，对于没什么经验，初上手开发游戏的新人来说收益也不多，所以打算在游戏机制等方面做些删减和取舍，游戏类型就先确定为2D末世风探索类游戏好了。

关于游戏的故事方面，我打算采用非线性的故事讲述机制，允许玩家自发探索，自发触发故事和剧情。因为考虑到如果用传统的一些游戏的任务机制的话，会给玩家带来约束感，无法带给玩家脱离社会的自由与心灵纯净的感受。可以先试试用inky写一些故事事件，来丰富与完善游戏方面的剧情。以及，并不打算在游戏中对背景之类的进行太多的解释和塑造。

至于引擎方面，之前本来打算用Unreal或Unity，不过看了一些相关的文章之后，发现还是Godot更适合我目前的情况和个人的需求，尤其是对于2D游戏开发方面的需求，此外可以节省性能，毕竟自家电脑本身的设备配置也不算高。准备先开始着手试做几个场景。

美术方面的话，虽然本人美术功底很差，不过或许还是可以绘制和修改一些图片，在找到好的绘师前，暂时先借助网上的一些免费素材，大致表达下自己想法就行。这样等实际发布和测试的时候，再找绘师做一套更好的素材用于替换，这样可以节省不少开发成本。

目前想到的大概就这么多吧，有什么别的想法之后再补充好了。