#+title: 【阅读笔记】哆啦A梦大雄的云之王国：天空人的隐喻
#+date: 2026-02-25T19:48:58
#+modified: 2026-02-26T13:18:25
#+tags: 天空人 哆啦A梦 云之王国 大雄的云之王国 藤子F不二雄 阅读笔记 个人感想 个人思考 叙事蒙蔽 政治 历史
#+summary: 虽然说这是阅读笔记，不过说实话其实这是篇杂谈。毕竟我也是读完这个系列很长一段时间后有比较多的反思，才开始写这个笔记的。作为一个有深度阅读过藤子F不二雄、加藤元浩等漫画家作品的创作者，一直都挺想给大家分享一下自己阅读这些漫画获得的感想和体会的。

* 前言
虽然说这是阅读笔记，不过说实话其实这是篇杂谈。毕竟我也是读完这个系列很长一段时间后有比较多的反思，才开始写这个笔记的。作为一个有深度阅读过藤子F不二雄、加藤元浩等漫画家作品的创作者，一直都挺想给大家分享一下自己阅读这些漫画获得的感想和体会的。

* 对个人而言印象最深刻的作品
翻开藤子F不二雄的哆啦A梦系列，对我而言印象最深刻的一部作品毫无疑问是大雄的云之王国。要说为什么印象最深刻，因为它不像铁人军团对军国主义的描写那么直接，甚至一开始你可能也会觉得云之王国里面的天空人是可以理解的、正义的一方。

当时看的时候并没有感觉哪里不对劲，直到事后了解了一些现实政治方面的事情，深切体会和感悟后，才开始感觉到云之王国这部作品是非常细思恐极的一部作品。

正是云之王国这种隐约不对劲的细思恐极的感觉，最能抓住我的内心，并在我心中留下了最深刻的印象。

* 故事脉路
要谈论这部作品的深度，首先得大致梳理下故事的脉路。

故事的开场从天空人诺亚计划的预演开始，在一个小岛上，一群神告诉岛上的人大洪水要来了，尽量做方舟逃离。他们没来得及离开，最终小岛被水淹没，然后上面的人被某种神秘力量吸走。

后来还有一幕，画面切换到偷猎者的视角，一群偷猎者追杀的大象和偷猎者一起被某种神秘力量吸到云上去了。

然后就是从轻松日常故事的开头开始了，大雄和哆啦等人在云上建立了一个自己的私人王国，然后孩子们在这个云上的私人王国玩得非常开心。

大雄等人偶然发现并搭救了一个神秘的人来到自己的王国，给他疗好伤后，得知他是从某种地方逃出来的。

后来这个人因为被天上人带走而失踪了，于是大雄等人就开始去找人，偶然和天上人接触，于是他们在天上人的邀请下就来到了他们的自然保护区。

这个自然保护区收容了许多因为人类破坏环境而灭绝的珍稀物种，其中还包括了小矮人文明，和开篇的时候被天上人吸走的那一家人。

然后他们来到这里住宿，偶然触碰某种开关，然后发现天上人有点怪怪的，不让他们离开，于是他们就决定逃离，但最后走散了，哆啦坏掉了，大雄也只能藏起来了，而其他人都被云之王国的人抓住，明天要带去中央州。

大概应该是差不多是到中央州的这个时间点，天上人才透露出诺亚计划和审判的事情，特别是作为天上人特工的那个小姐姐，用一脸天真和富有亲和力的表情解释他们的诺亚计划，因为他们的生存环境遭到了威胁，所以必须摧毁整个地表文明，当然所有地上的人都会被他们收容进自然保护区。

毕竟这也是迫不得已的事情，所以他们才会要抓住大雄等人，让他们代表地上人在法庭上审判，并不会让他们把诺亚计划的秘密告诉地上人，给他们戴上监听器，让他们无论如何逃跑都会被追踪到。

此前代表地上人在法庭上接受审判的是那群偷猎者，大象的证词让他们无法反驳，后来轮到静香等几个孩子，似乎也无法反驳证词。

而大雄这边正好在小人族和这边收容的人的帮助下修好了哆啦，并逃回到了自己的云之王国。后来偷猎者也偷走了天上人的飞行器，偶然逃到了大雄的云之王国，因为在这里带着王冠的大雄就是主人，所以天上人来这里也必须听从大雄的命令离开王国。

大雄他们为了救静香等人就决定用自己的武器：云还原剂来威胁天上人妥协。但因为威胁的时候王冠意外被偷猎者劫走，然后大雄等人都被关进了大牢里面。另外似乎还有个潜入进来交涉的小姐姐特工，也因为被发现关在了一起。

因为大雄等人只是威胁一下，并不真正打算毁灭天上人的国度，于是哆啦挺身而出，用自己的铁头功摧毁了云还原剂，从而阻止了偷猎者的阴谋。

后来审判因为有很多人辩护，最终打动了天上人，于是天上人决定移民到别的星球，再观察下地球的环境，等什么时候环境变好了再回来。

* 天空人的逻辑
梳理了很长的故事脉路，接下来就是要谈论的重点了，关于天空人的逻辑。

当时看故事的时候我其实对天上人并没有多少感觉，恰恰觉得他们的行为都非常合理，毕竟地上人破坏环境带来严重的问题，为了生存的动机也是完全可以理解的，他们毁灭的也只是地上人的文明，并不打算杀死所有地上人，而是将他们收容在自然保护区，让他们过上衣食无忧的生活。

但当你仔细品味这话，更多地去仔细品味他们说的这些话术，就会明显地察觉到不对劲了：
- 为了地球的和谐，我们要毁灭整个地上人的文明。
- 地上人破坏地球生态环境，所以他们有罪，我们必须毁灭整个地上人的文明。
- 别担心，没有人会受伤的，因为我们会将所有地上人都收容在自然保护区。
- 我们所做的只是抹杀地表的文明痕迹，让地上人与文明社会接轨。

这样应该就能察觉到明显的不对劲，甚至令人毛骨悚然的感觉了。

首先，毁灭整个文明这话，是能用那么轻松的口吻说出来的吗？

地上人的文明破坏地球的生态环境确实是事实，但是以此给他们定罪，并打着冠冕堂皇的口号说：“因为他们有罪，所以他们不是人，我们要毁灭整个地上人的文明？”，这是不是非常像是某种殖民者所说的理由？

并且他们决定将地上人收容在自然保护区，所以没有人会受伤，这一点，更加能体现的是，天空人并不打算给地上人的文明人权，因为他们破坏环境，所以他们不是人，因为他们不是人，所以我们把他们收容在自然保护区，让他们受到我们的统治也是正义之举。

是不是看出来了？这就是天空人的逻辑，也是他们的恐怖之处。

铁人军团好歹不会用这套正义包装掩盖自己的叙事，他们只会说我们就是神选之民，就是高人一等，所以我们要把别的文明全部抓去做奴隶，所有背叛我们的叛徒都得死。

但天空人不会这么说，他们不会直接说任何激烈的言辞，甚至表现出一种非常恐怖的理性。

只会像那个一脸天真，富有亲和力的小姐姐一样，微笑着说：“出于某种无奈的原因，被地上人破坏环境逼到绝路的我们，只能要摧毁地表上的所有文明。这也是经过议会的慎重考虑，放心，谁也不会受伤的。”

于是，这个逻辑链条就能成立了：

地上人破坏地球的生态环境->地表人是蛮族，他们不文明，所以必须被收容->地表人全都无可救药，我们必须毁灭他们的文明->我们受到他们的威胁，别无选择，只能毁灭他们。

此外，他们还会通过一个形式上的审判，在公众面前确证地表人的罪行，从而给自己一个，自己的决策全都是经过理性考虑的结果，这样的包装。

但实际上，他们审判也存在明显的不公正。审判选择的对象，有偷猎者，还有大雄等几个小孩子，出的证据和证人也全都是对地表人不利的证据，像是被偷猎者偷猎的大象等。

特别是那几个小孩子被作为地上文明的代表来进行决定毁灭整个文明的审判，也许也是最讽刺的一点，毕竟，小孩子几乎没有在审判中为自己辩护和反驳的能力。

最后之所以解决问题，还是多亏了哆啦A梦的英勇举动和大雄以前帮助过的植物星大使还有小人们出庭作证为地上人辩护，最终天上人被打动从而放弃诺亚计划，毕竟童话也总是要有一个好的结局嘛。

由此可见，天空人逻辑链条中，最恐怖的地方，就在于叙事蒙蔽和伪装，他们能将所有黑的说成白的，能将自己的所作所为包装成看着非常合情合理的话术，甚至连一开始看这部作品的我都被天空人这套看似合理的话术说辞所欺骗了。

* 天空人的隐喻
现在说回来的就是天空人的隐喻了，首先我能想到的，自然是二战时期的日本军国政府。毕竟藤子F不二雄本身就是一个持反战立场的老左翼创作者了，所以政治隐喻不出意外大部分都会首先批判日本右翼。

虽然我对日本二战前后那段历史了解很少，几乎只能说是略有了解。

那个让几个小孩子在法庭上审判的桥段，和1938年日本政府在东京召开的“大东亚审判”这个法庭审判非常相似，都是单方面且没有任何辩护机会的不公正审判。

当时日本军国政府也是打着大东亚共荣圈和解放弱小民族的口号，将入侵和毁灭其它文明的行为，说成是正义的举动，就像是天空人用富有亲和力的口吻说出毁灭文明的话一般。

据说当时日本政府主流叙事经常会塑造一种我们四面都是敌人的幌子，并打着反对西方霸权主义和殖民的口号，实际上

还有日本政府对边缘群体的同化和强迫融入政策，似乎也和天上人那个收容其它文明的政策非常相似。

可以说，天空人的整个政府，就像是对二战时期那个日本军国政府的一个镜像隐喻。

不过，天空人这一隐喻的高明之处就在，它不仅仅可以是对日本右翼政府和话术的隐喻，而是可以引起一个系统性的反思。

如果我们是天空人，那么我们是否能不被天空人单方面的话术蒙蔽，而是了解真实情况呢？

毕竟，谁又能百分之百确认自己国家无论打着何种正当理由，像是常见的反西方霸权和殖民主义，或是解放和开化弱小国家的口号，主动发动的对外的战争，不会又一个天空人灭绝和抹除文明的理由呢？

实际上就我对网络的了解，或许我们都没办法自认为自己是理性的，不会被欺骗的。

就像我在接触Fediverse之前，也是一直对主流叙事深信不疑，直到接触Fediverse，了解了更广阔的世界后，才意识到原来我的认知也存在很多的局限性，当然，可能也是因为我一直都愿意不断地修正和改变自己的认知，改变自己所认为的事情，并乐于享受改变认知后发现新事物的过程吧。

当然，天空人的隐喻，其实不仅仅可以隐喻日本右翼镜像政府，它甚至可以更广泛地，代入到任何国家的政府，不管是那些民主国家还是非民主的国家，似乎都可以代入进去进行反思。

不管是过去的，美国对印第安人的历史旧账，或是古代中国的华夷之辩，又或是现在的各国霸权和政治操弄等，似乎这个天空人的隐喻代入进去都很合适，所以说，这个隐喻，它可以是一个更广泛的，跨越时代的，对各个政权和叙事蒙蔽的一个系统性的比喻。

* 理解这作品的契机
最后，我想谈谈让我对这部作品传达的内核真正开始有所理解的契机。实际上，一开始我是没有领会到这部作品的内核的，毕竟我一直都觉得天上人所做的事情和与大雄等人的冲突，似乎从逻辑上还算合理，也说得通，能理解他们的苦衷。

但可能也是当时我阅读这部作品的时候积累的阅历还比较浅，并没有很深刻理解，或者Get到这部作品的隐喻。

直到后来我进入Fediverse的时候，通过Fediverse这个渠道，开始脱离了国内主要平台的一个叙事蒙蔽和算法牢笼，开始了解到更多元的声音，同时也深刻体会到各个国家和地区的文化差异和政治叙事差异造成的鸿沟究竟有多大。

通过Fediverse了解到更多元的视角之后，我个人的价值观也是发生了很大的变化，开始对国家本身有更多深刻的理解和思考了，以前我都是希望尽可能避免政治话题的，现在来看其实逃避这些冲突是没用的，毕竟政治和个人生活与权利息息相关，但我们可以自己选择更理性一点的立场。

就像是国内许多人并不知道一些国内某些被掩盖的事情一样，国外许多人也习惯性地被国外的叙事蒙蔽欺骗，或许正是这种叙事蒙蔽是双向的，所以不同国家的人才会造成如此大的认知鸿沟，相互敌对和冲突吧。但实际上如果去了解他们，你会发现其实很多人还是相对友善的。

很多被贴某种标签的人并没有我们想象的那么排外和偏激，虽然确实也是比较有些立场比较偏激，但我感觉其实相对都比较占少数了，X等平台感觉就是个不断放大情绪的地方，自然容易出现很多非常偏激的言论，像极了以前偏信单方面消息然后疯狂转发的我（bushi）。

不过自从了解Fediverse后，我感觉我多少也回归理性了不少，没那么容易偏信单方面信息了。

所以我觉得，看到立场不同的东西，最好多去了解他们立场为什么不同，尽量听取多方立场交叉验证。不要只偏信任何一方的单方面说辞。

政府本身也不是完全可信的，他们更倾向于维持对自己所代表的利益群体有利的立场，多了解了国家和政治之后，也能深切体会到政治说白了都是一个做蛋糕和分蛋糕的问题，但就是因为这个问题引发了各种权力斗争，就像前面所讲的天空人的隐喻那样。

总之就是，要避免这种单方面的叙事蒙蔽无论是来自政府的、个人的或任何群体的叙事蒙蔽，最好的办法还是尽量不要总是呆在国内平台或者任何一个会放大极端声音的算法平台，多出去走走，多接触下像是Fediverse、Blog和RSS这类去算法推送机制的信息源，多倾听和自己意见不同的声音，不要急着给别人贴标签。