#+title: 创作的信心：乐趣与享受
#+date: 2026-02-23T20:03:57
#+modified: 2026-02-26T13:49:37
#+tags: 创作 创作感想 信心 返璞归真 乐趣 创作的乐趣 个人思考
#+summary: 突然关于想起很久以前失去的一个朋友的事，于是就特别想写这么一篇文章了。	我还记得几年前，我的一个朋友曾和我聊过关于创作的话题，大意是你无法理解，创作是痛苦的，那种不断给自己期望却无法满足无法触及的感觉。
* 创作的信心：乐趣与享受
突然关于想起很久以前失去的一个朋友的事，于是就特别想写这么一篇文章了。

我还记得几年前，我的一个朋友曾和我聊过关于创作的话题，大意是你无法理解，创作是痛苦的，那种不断给自己期望却无法满足无法触及的感觉。

其实，我还记得上初高中时期的我，一直都会被自己创作能力不足的事所困扰，因为总是觉得创作就是要写出什么了不起的成果给别人看的，因为一直有这种心态，一旦我想写出什么理想的东西，最后发现我什么东西都做不好的时候，确实一度感到心灰意冷，很长一段时间在我看来，创作都是很痛苦的事情。

不过后来，事情有了转机。我决心脱离旧的社交关系，淡出了旧的圈子，加入了动物朋友社团，看了斋藤直葵老师的绘画课程，也开始逐步意识到，也许什么都做不好，其实没那么可怕，因为创作本质上不是追求什么了不起的成果那么一回事。

接触到了一个不同的世界和一个不同的价值观的时候，我才意识到，原来还有这种可能性。

其实，我们并不需要去追求什么成果，因为创作的乐趣是在于享受创作的作品的过程。

像是：
- 写作，乐趣来自构思世界观、构思故事剧情的过程。
- 写文章，乐趣来自思考和整理思路的过程。
- 画画，乐趣来自流畅地动笔的爽感。
- 编曲，乐趣来自摸索和弦组合的过程。
- 做游戏，乐趣来自迭代和构思游戏思路的过程。

虽然是看起来很简单的道理，但实际情况可能并不简单，也许我们经常会因为太在意某些外部评价，太期望某些人的评论，或者因为自己审美觉得自己做得不够好，就轻易地否决自己做的成果。

不过实际上是，我们根本不可能创作出让任何人都满意的作品，自己的创作水平固然不足，但不要忘记的是，创作本身其实就是一个循序渐进地，成长的过程。

就像我们常说，人生是马拉松长跑，不是短暂的旅途，人生是旷野，不是轨道一样。

我也可以说，创作是一段长途享受的旅途，真正重要的不是结果，而是看到自己成长的过程。

就像小孩子学习画画，也并不需要在意他人评价或自己评价，只需要尽情地放空大脑，放飞想象力，画出自己能想到的东西，并享受这种天马行空地实现和发挥创意带来的乐趣。

当然我也不是说创作不需要进步，而是觉得，创作其实也可以像是类比Linux折腾一样的事情，乐趣都来自摸索事情该怎么做。

所以，其实我们根本就不需要在意自己创作的成果怎么样，不需要消极地自我评价自己的作品有多糟糕，因为这不是重点。

真正重要的其实是，通过创作来探索可能性，以及塑造可能性。抱着这样的心态的话，其实每次有新发现的时候，都会有一种很不可思议的感觉吧。

还有，创作这件事，也许本身和水平是无关的，它其实更多的是个人经验的凝练和表达，只要能通过创作，将个人经验凝结并表达出来，尽力去做，就已经足够好了。

之所以有些创作者很有自信心，外人看来感觉很厉害，或许也是因为这些创作者拥有某种返璞归真的能力，就像是动物朋友的创作者たっき监督那样，因为有过某种在非洲大草原奔跑游历的经历，所以才能更深切地塑造出动物朋友的那种情境感吧。

这类创作者往往并不会太过在意世俗的名利得失，他们更在意的或许还是，能不能分享某种乐趣，能不能通过创作获得某种满足。但也正是像这样通过塑造自己的精神境界和世界观，才能创作出不可思议的作品。

也许，没有过返璞归真地创作经历的人，是很难体会这点的吧，大概就像是我过去失去的那个朋友那样，他走进了某种创作必须要让作品完美符合自己的审美，或者必须要做出自己觉得非常了不起的作品的误区。

在我个人看来，这就像是结果一样，如果一味地执着于获得某种成果，不懂得像孩子一般享受某种乐趣的话，或许也只会变成又一个无聊的大人吧。