#+title: 最近做gamejam练习作的一些心得
#+date: 2022-06-07T15:33:42
#+modified: 2026-03-01T15:38:31
#+tags: 日志归档 游戏日志 创作日志 gamejam 心得 个人感想
#+summary: 好久没写日志了，离CIGAgamejam2022只有20天左右了，最近正好在做些小游戏练习下，提升策划水平。以及重新整理下创作思路，往更可行的方向发展。	因为缺乏gamejam的经验，所以最近和队伍里的伙伴一起商量了下做个练习作，选的是2020年的gamejam题材，一开始立项的时候还算顺利，没遇到什么问题。
好久没写日志了，离CIGAgamejam2022只有20天左右了，最近正好在做些小游戏练习下，提升策划水平。以及重新整理下创作思路，往更可行的方向发展。

因为缺乏gamejam的经验，所以最近和队伍里的伙伴一起商量了下做个练习作，选的是2020年的gamejam题材，一开始立项的时候还算顺利，没遇到什么问题。

立项阶段的时候经过一些讨论商议，和一些评估，最终确定了是要做一款消除方块和围堵蚂蚁为玩法的推箱子小游戏，不过这一阶段并没有把主要机制评估清楚，导致加入了一些严重拖慢制作时间和进度的内容。

比如立项时候我们还打算做一个类似俄罗斯方块的旋转机制，但是当时并没考虑到这个机制可能会极大地增加游戏的复杂性和程序的实现成本，对于新手程序策划来说无疑是个调整，结果到了开始制作游戏阶段的时候，为了一个旋转机制和消除方块判定方面的兼容，消耗了差不多2天时间。

关卡设计也是因为直到开始制作的第三天，决定要消除旋转这个机制之后，又不得全部推翻重来，因此到做出成品的时候，花费的时间比预期多了整整2天。

到第三天的时候，因为我代码方面感觉已经看不到什么要调整的了，于是认真思考了和调整了下关卡设计，多想了想怎样设计的关卡比较有趣，试着运用了下在《独立游戏设计艺术》一书中学到的兴趣曲线理论，到第四天测试的时候，发现效果挺显著。

第四天的时候我把这款游戏的可玩办法发给群友们测试，直到发给他们测试，他们指出了我的游戏存在的一些问题的时候，我才发现beta阶段的意义其实非常重要，因为有很多问题只有给团队之外的人测试，让他们以玩家的身份玩这款游戏的时候才能发现。

还有就是关于美术方面，因为我提出的需求并不够明确，没有样本图给美术参考，因此美术做出的作品策划方面的设计配合得并不是很好，但这方面我通过一些取舍和自己利用素材的方式，也成功解决了这方面的问题，下次的话最好还是要给美术提出更明确的要求，如果有样本图就更好了。

这次小游戏制作的练习中，我学到了很多很多东西，比如游戏设计方面要学会进行取舍，不然到后面再取消一些设计，会极大增加制作的成本，以及收获了一些可贵的团队协作经验。

这次小游戏制作的时候，美术和音乐没有拖后腿，反而是作为程序和策划的本人拖了不少后腿，不过有了这次经验，希望这次正式gamejam的时候也会顺利些吧。

以下是我练习作做出的成品，欢迎大家试玩：

https://wwd.lanzouw.com/iMhXQ061vxtg