#+title: 终末之旅开发日志#3
#+date: 2021-12-10T15:40:36
#+modified: 2026-03-01T15:40:36
#+tags: 终末之旅 日志归档 游戏日志 创作日志
#+summary: 今天也是崭新的旅途诶，小雨～	考虑到对一款游戏来说，角色对玩家体验来说也是非常重要的一部分，所以我的原型决定先从角色开始设计，把角色的主要动作完善好了之后再设计游戏的基本机制和地图设计。这周主要的工作就是设计角色和绘制动作图了。由于我并不熟悉绘画这方面的技能，所以绘画的时候比较勉强，花费了不少时间找参考以及调整角色设计，终于在这周做出了两个主要角色的设定图、正面站立图和45度侧面行走图。
今天也是崭新的旅途诶，小雨～

考虑到对一款游戏来说，角色对玩家体验来说也是非常重要的一部分，所以我的原型决定先从角色开始设计，把角色的主要动作完善好了之后再设计游戏的基本机制和地图设计。这周主要的工作就是设计角色和绘制动作图了。由于我并不熟悉绘画这方面的技能，所以绘画的时候比较勉强，花费了不少时间找参考以及调整角色设计，终于在这周做出了两个主要角色的设定图、正面站立图和45度侧面行走图。

开始本来打算用更为精致的素材和更符合氛围的美术风格，不过经过考虑，还是发现像素艺术风格可以在成本更低的情况下表现出我想要的效果，因此我换成了像素艺术风格。尽管我花费了不少时间调整和完善做出了这些素材，不过素材制作依然是比较粗略简陋，没有进行手工抗拒齿，也只是基本地上了色，没有加入太多光影，且素材中的人体结构还有待调整，特别是行走图中的人体表现得特别畸形和诡异。

不过至少这次的素材比之前的素材都要好一些了，更符合我想要的创作要求。

对于程序方面，这周本来打算完善角色的动作和操作，不过也就写了几段代码而已，毕竟让角色能够互动，是作为游戏的基础，况且我的游戏重点在于伙伴互动，因此更需要在角色动作和伙伴互动系统方面下工夫创作，尽可能来想办法给玩家塑造出角色之间纯纯的情感的那种温馨感。

至于故事方面，今天写了份开场故事的文案，在文案中顺带完善了小风和小雨的基础性格设定，确立了一段引入开场的剧情，以及关于小风背上的那双小翅膀的讨论。

不过文案方面这次我就不发了，涉及到剧情透内容的东西，我决定留给和我一起创作的伙伴讨论（也不算是一起创作的伙伴，只能算是给我提建议的那几个人）。

以下为小风、小雨的人设图及一张角色行走图模板，图和人设未经允许不得转载和盗用：
https://hive.indienova.com/farm/blog/2021/12/u-4025458519112yTh.png
https://hive.indienova.com/farm/blog/2021/12/u-40254585191361Wi.png
https://hive.indienova.com/farm/blog/2021/12/u-4025458519148JFV.gif